# Generated by Django 3.2.7 on 2024-05-01 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Area',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'Asignaturas',
                'ordering': ['colegio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Ciclos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Ciclos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'Colegio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=1)),
                ('colegio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ltr.colegio')),
            ],
            options={
                'db_table': 'Curso',
                'ordering': ['colegio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'EstadoTarea',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estadoticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'EstadoTicket',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.IntegerField()),
                ('ciclo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.ciclos')),
            ],
            options={
                'db_table': 'Nivel',
                'ordering': ['ciclo', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=80)),
                ('cargo', models.CharField(default='', max_length=80)),
                ('esprofe', models.BooleanField(default=False)),
                ('colegio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.colegio')),
            ],
            options={
                'db_table': 'Personas',
                'ordering': ['esprofe', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('profejefe', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.area')),
            ],
            options={
                'db_table': 'SubArea',
                'ordering': ['area'],
            },
        ),
        migrations.CreateModel(
            name='TipoRespuestaColegio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Tiporespuestacolegio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'TipoTarea',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipocontacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('color', models.CharField(default='#FFFFFF', max_length=10)),
                ('colegio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.colegio')),
            ],
            options={
                'db_table': 'TipoContacto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=80, null=True)),
                ('motivo', models.TextField()),
                ('fechaactualizacion', models.DateTimeField(auto_now=True)),
                ('fechahoracambioestado', models.DateTimeField(blank=True, null=True)),
                ('nombrealumno', models.CharField(default='', max_length=80)),
                ('apellidoalumno', models.CharField(default='', max_length=80)),
                ('fechaprimerenvio', models.DateTimeField(blank=True, null=True)),
                ('fechaprimerarespuesta', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.asignatura')),
                ('curso', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.curso')),
                ('estadoticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.estadoticket')),
                ('nivel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.nivel')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.subarea')),
                ('tipocontacto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.tipocontacto')),
            ],
            options={
                'db_table': 'Ticket',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now=True)),
                ('fechavencimiento', models.DateField()),
                ('detalle', models.CharField(max_length=80)),
                ('estadotarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.estadotarea')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.ticket')),
                ('tipotarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.tipotarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tarea',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Seguimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableSuperior',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.personas')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.subarea')),
            ],
            options={
                'db_table': 'ResponsableSuperior',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableSubareaNivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.nivel')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.personas')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.subarea')),
            ],
            options={
                'db_table': 'ResponsableSubareasNivel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorResponsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.asignatura')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.nivel')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.personas')),
            ],
            options={
                'db_table': 'ProfesorResponsable',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorJefe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.curso')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.nivel')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.personas')),
            ],
            options={
                'db_table': 'ProfesorJefe',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechora', models.DateTimeField(auto_now_add=True)),
                ('correoemisor', models.CharField(max_length=80)),
                ('correodestino', models.CharField(max_length=80)),
                ('respondido', models.BooleanField(default=False)),
                ('asunto', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.ticket')),
            ],
            options={
                'db_table': 'Mensajes',
                'ordering': ['fechora'],
            },
        ),
        migrations.CreateModel(
            name='CoordinadorCiclo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.ciclos')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.personas')),
            ],
            options={
                'db_table': 'CoordinadorCiclos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ciclos',
            name='colegio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ltr.colegio'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.colegio'),
        ),
        migrations.AddField(
            model_name='area',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.colegio'),
        ),
    ]
