# Generated by Django 3.2.7 on 2024-04-06 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Area',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Cargo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'Colegio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Curso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'EstadoTarea',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estadoticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'EstadoTicket',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Nivel',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.area')),
            ],
            options={
                'db_table': 'SubArea',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=80, null=True)),
                ('motivo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('fechahoracambioestado', models.DateTimeField(null=True)),
                ('estadoticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.estadoticket')),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.subarea')),
            ],
            options={
                'db_table': 'Ticket',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'TipoTarea',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipocontacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.colegio')),
            ],
            options={
                'db_table': 'TipoContacto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TicketAlumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.curso')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.nivel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.ticket')),
            ],
            options={
                'db_table': 'TicketAlumno',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipocontacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.tipocontacto'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now=True)),
                ('fechavencimiento', models.DateField()),
                ('detalle', models.CharField(max_length=80)),
                ('estadotarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.estadotarea')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.ticket')),
                ('tipotarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.tipotarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tarea',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechahora', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Seguimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=80)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.cargo')),
            ],
            options={
                'db_table': 'Responsable',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.colegio'),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idresp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.responsable')),
                ('idsubarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.subarea')),
            ],
            options={
                'db_table': 'Asignacion',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.colegio'),
        ),
    ]
