# Generated by Django 3.2.7 on 2024-04-06 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocontacto',
            old_name='colegio',
            new_name='cole',
        ),
    ]
