# Generated by Django 3.2.7 on 2024-05-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadoticket',
            options={'ordering': ['id']},
        ),
    ]
