# Generated by Django 3.2.7 on 2024-05-02 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0002_alter_estadoticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ltr.personas'),
        ),
    ]
