# Generated by Django 3.2.7 on 2024-05-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0003_mensaje_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='idmensajerespondido',
            field=models.IntegerField(default=0),
        ),
    ]
