# Generated by Django 3.2.7 on 2024-05-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0004_mensaje_idmensajerespondido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='idmensajerespondido',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
