# Generated by Django 3.2.7 on 2024-04-10 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0004_auto_20240409_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subarea',
            options={'ordering': ['area']},
        ),
        migrations.AddField(
            model_name='ciclos',
            name='colegio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ltr.colegio'),
        ),
    ]
