# Generated by Django 3.2.7 on 2024-04-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0006_nivel_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['ciclo', 'orden']},
        ),
        migrations.AlterField(
            model_name='nivel',
            name='orden',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
