# Generated by Django 3.2.7 on 2024-05-16 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0007_auto_20240516_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticketcorrelativo',
        ),
    ]
