# Generated by Django 3.2.7 on 2024-05-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0008_delete_ticketcorrelativo'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Motivocierre',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('nombre', models.CharField(max_length=100)),
        #     ],
        #     options={
        #         'db_table': 'MotivoCierre',
        #         'ordering': ['id'],
        #     },
        # ),
        migrations.AddField(
            model_name='ticket',
            name='personacierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.personas'),
        ),
        migrations.AlterField(
            model_name='tiporespuestacolegio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
