# Generated by Django 3.2.7 on 2024-04-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0008_alter_nivel_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['colegio', 'orden']},
        ),
        migrations.AddField(
            model_name='curso',
            name='colegio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ltr.colegio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
