# Generated by Django 3.2.7 on 2024-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0009_auto_20240410_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocontacto',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
    ]
