# Generated by Django 3.2.7 on 2024-04-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0010_tipocontacto_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fechahoracambioestado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
