# Generated by Django 3.2.7 on 2024-05-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0010_alter_ticket_personacierre'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Motivocierre',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('nombre', models.CharField(max_length=100)),
        #     ],
        #     options={
        #         'db_table': 'MotivoCierre',
        #         'ordering': ['id'],
        #     },
        # ),
    ]
