# Generated by Django 3.2.7 on 2024-04-13 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0011_alter_ticket_fechahoracambioestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='timestamp',
            new_name='fechaactualizacion',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='fecha',
        ),
        migrations.AddField(
            model_name='ticket',
            name='fechacreacion',
            field=models.DateField(default=datetime.date(2024, 4, 12)),
        ),
    ]
