# Generated by Django 3.2.7 on 2024-05-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0011_motivocierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivocierre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'MotivoCierre',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='motivocierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.motivocierre'),
        ),
    ]
