# Generated by Django 3.2.7 on 2024-04-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0012_auto_20240413_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
