# Generated by Django 3.2.7 on 2024-05-25 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ltr', '0012_auto_20240523_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoColegio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colegioactual', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actual_acceso_colegio', to='ltr.colegio')),
                ('colegiodefault', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_acceso_colegio', to='ltr.colegio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AccesoColegio',
                'ordering': ['user'],
            },
        ),
    ]
