# Generated by Django 3.2.7 on 2024-04-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0013_alter_ticket_fechacreacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsignacionDirectorio',
            new_name='CoordinadorCiclo',
        ),
        migrations.RenameModel(
            old_name='AsignacionResponsable',
            new_name='ResponsableSubareaCiclo',
        ),
        migrations.RenameModel(
            old_name='AsignacionJefatura',
            new_name='ResponsableSuperior',
        ),
        migrations.AlterModelTable(
            name='coordinadorciclo',
            table='CoordinadorCiclos',
        ),
        migrations.AlterModelTable(
            name='responsablesubareaciclo',
            table='ResponsableSubareasCiclos',
        ),
        migrations.AlterModelTable(
            name='responsablesuperior',
            table='ResponsableSuperior',
        ),
    ]
