# Generated by Django 3.2.7 on 2024-05-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0014_auto_20240528_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='numticket',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='personacierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.personas'),
        ),
    ]
