# Generated by Django 3.2.7 on 2024-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0014_auto_20240417_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='cargo',
            field=models.CharField(default='', max_length=80),
        ),
    ]
