# Generated by Django 3.2.7 on 2024-04-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0015_personas_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.colegio')),
            ],
            options={
                'db_table': 'Asignaturas',
                'ordering': ['colegio', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorJefe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.curso')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.nivel')),
            ],
            options={
                'db_table': 'ProfesorJefe',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorResponsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.asignatura')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.nivel')),
            ],
            options={
                'db_table': 'ProfesorResponsable',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableSubareaNivel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.nivel')),
            ],
            options={
                'db_table': 'ResponsableSubareaNivel',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='personas',
            name='colegio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.colegio'),
        ),
        migrations.AddField(
            model_name='personas',
            name='esprofe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subarea',
            name='profejefe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coordinadorciclo',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.ciclos'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='responsablesuperior',
            name='subarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.subarea'),
        ),
        migrations.DeleteModel(
            name='ResponsableSubareaCiclo',
        ),
        migrations.AddField(
            model_name='responsablesubareanivel',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.personas'),
        ),
        migrations.AddField(
            model_name='responsablesubareanivel',
            name='subarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.subarea'),
        ),
        migrations.AddField(
            model_name='profesorresponsable',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.personas'),
        ),
        migrations.AddField(
            model_name='profesorjefe',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltr.personas'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='aisgnatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.asignatura'),
        ),
    ]
