# Generated by Django 3.2.7 on 2024-04-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0016_auto_20240423_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='responsablesubareanivel',
            table='ResponsableSubareasNivel',
        ),
    ]
