# Generated by Django 3.2.7 on 2024-06-10 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0016_ticketcerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcerrado',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ltr.personas'),
        ),
    ]
