# Generated by Django 3.2.7 on 2024-04-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0017_alter_responsablesubareanivel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'ordering': ['esprofe', 'nombre']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='fechaprimerarespuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fechaprimerenvio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
