# Generated by Django 3.2.7 on 2024-07-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0018_area_nombreabr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fechaaviso2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fechaaviso4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
