# Generated by Django 3.2.7 on 2024-07-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0019_auto_20240709_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fechaaviso4',
            new_name='fechaaviso3',
        ),
    ]
