# Generated by Django 3.2.7 on 2024-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltr', '0020_rename_fechaaviso4_ticket_fechaaviso3'),
    ]

    operations = [
        migrations.AddField(
            model_name='subarea',
            name='nocopiaciclo',
            field=models.BooleanField(default=0),
        ),
    ]
